# FROM eclipse-temurin:17-jdk-jammy
#
# WORKDIR /app
#
# COPY .mvn/ .mvn
# COPY mvnw pom.xml ./
# RUN ./mvnw dependency:resolve
#
# COPY src ./src
#
# CMD ["./mvnw", "spring-boot:run"]

FROM eclipse-temurin:17-jdk-alpine
EXPOSE 8080
ADD ./Tipout-0.0.1-SNAPSHOT.jar Tipout-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Tipout-0.0.1-SNAPSHOT.jar"]